name: rolodoct
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  lottie: ^3.3.1
  animated_text_kit: ^4.2.3
  faded_text: ^0.0.11
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
