// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0ISBTe0k3qI9RXMuLnIqtTUCr3keDvmk',
    appId: '1:325182710551:web:4928327ea2de95cd57cd52',
    messagingSenderId: '325182710551',
    projectId: 'rulerdoct-v1',
    authDomain: 'rulerdoct-v1.firebaseapp.com',
    storageBucket: 'rulerdoct-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD-gxF4ID1eE88M1FIFMe75iZHfVvLxfg',
    appId: '1:325182710551:android:8e71ba2787c547e157cd52',
    messagingSenderId: '325182710551',
    projectId: 'rulerdoct-v1',
    storageBucket: 'rulerdoct-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZtar40HI9-hHRpbQVVt2XRvFhkDN0b1Q',
    appId: '1:325182710551:ios:47a8e58efd75a88857cd52',
    messagingSenderId: '325182710551',
    projectId: 'rulerdoct-v1',
    storageBucket: 'rulerdoct-v1.firebasestorage.app',
    iosBundleId: 'com.example.rolodoct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZtar40HI9-hHRpbQVVt2XRvFhkDN0b1Q',
    appId: '1:325182710551:ios:47a8e58efd75a88857cd52',
    messagingSenderId: '325182710551',
    projectId: 'rulerdoct-v1',
    storageBucket: 'rulerdoct-v1.firebasestorage.app',
    iosBundleId: 'com.example.rolodoct',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0ISBTe0k3qI9RXMuLnIqtTUCr3keDvmk',
    appId: '1:325182710551:web:e6dc23d16cfe574c57cd52',
    messagingSenderId: '325182710551',
    projectId: 'rulerdoct-v1',
    authDomain: 'rulerdoct-v1.firebaseapp.com',
    storageBucket: 'rulerdoct-v1.firebasestorage.app',
  );
}
